name: Default
priority: 1
count: 0
maps:
- OutCast
- Warlock
- Monday
- Agrostid
- "Settler's Covert"
- Persisto
- Assault
- Dorreak Half
- Croak
- Dwyer Hill
- Desolated Frontier
- Rolexius
- Seahold
- Nucleus
- Gralien
- BalloonsDTM
- Justice
