name: Default
priority: 1
count: 0
maps:
- OutCast
- Warlock
- Dorreak Half
- Assault
- Persisto
- Croak
- Agrostid
- SuperCube
- Desolated Frontier
- Ringround
- "Settler's Covert"
- Placid Spring
- BalloonsDTM
- Seahold
- Justice
- Rolexius
- Dwyer Hill
- Gralien
