name: Default
priority: 1
count: 0
maps:
- Warlock
- Gralien
- Abaddon KOTH
- Fairy Tales 2: Mini
- Diramu Valley DTM
- Dorreak Half
- Remnant Souls
- Xi II
- Loyalty DTM
- Persisto
- Blitzkrieg CTF
- "Hot Dam: Mini"
- Agrostid
- Hoi
- Snowy Wars
- Monday

