name: Default
priority: 1
count: 0
maps:
- Snowy Wars
- Monday
- Remnant Souls
- Dorreak Half
- Warlock
- Gralien
- Abaddon KOTH
- Agrostid
- Loyalty DTM
- Xi II
- Skyline
- "Hot Dam: Mini"
- Persisto
- Blitzkrieg CTF
- Diramu Valley DTM
- Battle Ecliptica II
