name: Default
priority: 1
count: 0
maps:
- Diramu Valley DTM
- Monday
- Remnant Souls
- Infernal Shadow
- Warlock
- Xi II
- Blitzkrieg CTF
- Gralien
- Loyalty DTM
- Agrostid
- Tamblanor RAGE
- "Hot Dam: Mini"
- Dorreak Half
- Skyline
- Snowy Wars
- Battle Ecliptica II
